name: "DEBUG"
on:
  workflow_dispatch:
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-latest
    
    steps:
     - name: dd
       run: |
        ls -la
        echo ${{ secrets.SMS_USERNAME }}
      
