name: "DEBUG"
on:
  workflow_dispatch:
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-latest
    
    steps:
     - name: dd
       env:
          SUPER_SECRET: ${{ secrets.SUPABASE_URL }}
       run: |
          echo "$SUPABASE_URL"
